/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

import uk.org.dft_bluebadge.Arg;
import uk.org.dft_bluebadge.ArgValidator;

public class ArgumentValidatorTest {
    @Test 
    public void testNotNullThrowsIllegalArgumentException() {
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
          ArgValidator.validate(null, (String x) -> Arg.NotNull(x), "DB_HOST");
        });
    }

    @Test
    public void testReturnsValue(){
      String expected = "fubar";
      String actual = ArgValidator.validate(expected, (x) -> Arg.NotNull(x), "fubar");
      assertEquals(actual, expected);
    }
}
