/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.jupiter.api.BeforeEach;
import org.junit.jupiter.api.Test;

import static org.junit.jupiter.api.Assertions.*;

import uk.org.dft_bluebadge.infrastructure.PostgresConfiguration;

public class PostgresConfigurationTest {

    @Test
    public void testRequireHost(){
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
          new PostgresConfiguration(null, "", "", "");
        });
        assertEquals("host", exception.getMessage());
    }

    @Test
    public void testRequireDatabase(){
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
          new PostgresConfiguration("", null, "", "");
        });
        assertEquals("database", exception.getMessage());
    }

    @Test
    public void testRequireUser(){
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
          new PostgresConfiguration("", "", null, "");
        });
        assertEquals("user", exception.getMessage());
    }

    @Test
    public void testRequirePassword(){
        IllegalArgumentException exception = assertThrows(IllegalArgumentException.class, () -> {
          new PostgresConfiguration("", "", "", null);
        });
        assertEquals("password", exception.getMessage());
    }
}
